//#include "main.rs.h";  // This IS generated by cxx!
//#include "src/include/bridge.h"
#include "snes9x/messages.h"
#include <memory>

extern void rust_s9x_message(int info, int usage, const char *description);

extern "C" void S9xMessage(int type, int number, const char *message) {
    rust_s9x_message(type, number, message);
}

extern "C" void S9xExtraUsage() {
	return;
}
