[workspace]
resolver = "3"
members = ["core_bridge"]

[package]
name = "snes-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
core_bridge = { path = "core_bridge" }
wasm-bindgen = "0.2.101"
