[package]
name = "core_bridge"
version = "0.1.0"
edition = "2024"
links= "core_bridge"

[lib]
name = "core_bridge_lib"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
cxx = "1.0.0"
libc = "0.2"
wasm-bindgen = "0.2.101"

[build-dependencies]
cxx-build = "1.0"
